spring.application.name=biblioteko

spring.datasource.url=jdbc:h2:file:./data/librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=revature
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect